# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7ead5f37-a008-4692-a5af-b4cfa14770af";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5A83-2C64";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/STORAGE" =
    { device = "/dev/disk/by-uuid/6A8683BF86838A71";
      fsType = "ntfs";
    };

  fileSystems."/mnt/STORAGE2" =
    { device = "/dev/disk/by-uuid/236a8276-df19-4eb4-876a-0bbfba517fd6";
      fsType = "ext4";
    };

  fileSystems."/mnt/STORAGE3" =
    { device = "/dev/disk/by-uuid/2f91d672-1c58-4337-abc0-78ee8f3ed603";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/04c8cdb3-a776-44d9-a11f-7a942b24e11f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
